"""
Signal data model and persistence.

A Signal is the output of any detector — it's the moment where the bot
thinks "hey, MEXC is probably about to move because Binance just did X".

Every signal goes into the `signals` SQLite table for later analysis.
Signals are recorded for later analysis by downstream consumers.
"""
from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from typing import Any

import orjson

from src.storage.db import Database

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """
    A trading signal generated by any of the detectors.
    """
    symbol: str
    direction: str                  # "long" | "short"
    source: str                     # "static_gap" (only detector currently)
    confidence: float               # 0..1, detector-specific
    binance_price: float            # Binance mid at time of signal
    mexc_price: float               # MEXC mid at time of signal
    binance_impulse_pct: float = 0  # how much Binance moved in detector window
    mexc_lag_pct: float = 0         # how far MEXC is behind Binance (positive = behind)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at_ms: int = field(default_factory=lambda: int(time.time() * 1000))

    def __str__(self) -> str:
        return (
            f"Signal[{self.source}] {self.symbol} {self.direction.upper()} "
            f"impulse={self.binance_impulse_pct:+.4f}% "
            f"lag={self.mexc_lag_pct:+.4f}% "
            f"conf={self.confidence:.2f}"
        )


class SignalWriter:
    """Asynchronous batched writer for signals → SQLite."""

    def __init__(self, db: Database, flush_interval_sec: float = 1.0, max_batch: int = 100) -> None:
        self.db = db
        self.flush_interval = flush_interval_sec
        self.max_batch = max_batch
        self._queue: asyncio.Queue[Signal] = asyncio.Queue(maxsize=10_000)
        self._task: asyncio.Task | None = None
        self._stop = asyncio.Event()
        self.total_written = 0

    async def start(self) -> None:
        self._task = asyncio.create_task(self._flush_loop(), name="signal_writer")
        logger.info("SignalWriter started")

    async def stop(self) -> None:
        self._stop.set()
        if self._task:
            await self._task
        logger.info("SignalWriter stopped (total written=%d)", self.total_written)

    async def write(self, sig: Signal) -> None:
        """Non-blocking enqueue. Drops signal if queue overflows (logged)."""
        try:
            self._queue.put_nowait(sig)
        except asyncio.QueueFull:
            logger.warning("Signal queue overflow, dropping: %s", sig)

    async def _flush_loop(self) -> None:
        # Exception handling: catch Exception INSIDE the loop, log it,
        # sleep briefly to avoid tight-looping on persistent errors, then
        # continue. The only ways out are stop_event.set() and
        # CancelledError. Wrapping the whole loop in try/except would
        # kill the task on the first unhandled error and silently leak
        # signals into the queue until put_nowait starts dropping them.
        try:
            while not self._stop.is_set():
                try:
                    batch: list[Signal] = []
                    # Wait up to flush_interval for at least one item
                    try:
                        first = await asyncio.wait_for(
                            self._queue.get(), timeout=self.flush_interval
                        )
                        batch.append(first)
                    except asyncio.TimeoutError:
                        continue

                    # Drain remaining (non-blocking) up to max_batch
                    while len(batch) < self.max_batch:
                        try:
                            batch.append(self._queue.get_nowait())
                        except asyncio.QueueEmpty:
                            break

                    await self._write_batch(batch)
                except asyncio.CancelledError:
                    raise
                except Exception as e:
                    logger.exception(
                        "SignalWriter flush loop iteration error "
                        "(continuing): %s", e,
                    )
                    # Brief sleep to avoid tight-loop on a persistent failure
                    # (e.g. DB disk full, schema mismatch). 1s is short enough
                    # to recover quickly when the underlying issue clears.
                    await asyncio.sleep(1.0)
        except asyncio.CancelledError:
            return

    async def _write_batch(self, batch: list[Signal]) -> None:
        if not batch:
            return
        rows = [
            (
                s.symbol,
                s.direction,
                s.source,
                s.binance_impulse_pct,
                s.mexc_lag_pct,
                s.confidence,
                orjson.dumps(s.metadata).decode() if s.metadata else None,
                s.created_at_ms // 1000,  # store as unix seconds (consistent with other tables)
                0,  # consumed = false
                None,  # consumed_by = null
            )
            for s in batch
        ]
        # Bulk insert via executemany
        try:
            await self.db.conn.executemany(
                """INSERT INTO signals (
                    symbol, direction, source,
                    binance_impulse_pct, mexc_lag_pct, confidence,
                    metadata_json, created_at, consumed, consumed_by
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                rows,
            )
            await self.db.conn.commit()
            self.total_written += len(batch)
        except Exception as e:
            # ROLLBACK обовʼязково: інакше executemany лишає ВІДКРИТУ транзакцію
            # на спільному зʼєднанні -> усі подальші read'и застигають на старому
            # снапшоті до рестарту (баг привид-webkey у /webkey). Батч уже втрачено.
            try:
                await self.db.conn.rollback()
            except Exception:
                pass
            logger.exception("Signal batch write failed (%d signals lost): %s", len(batch), e)
